# Generated by Django 4.1.7 on 2023-03-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Title')),
                ('about', models.TextField(verbose_name='About')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('image', models.ImageField(upload_to='anime/images/', verbose_name='Image')),
                ('carousel', models.ImageField(upload_to='anime/carousel/', verbose_name='Image for carousel')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(auto_created=0, verbose_name='Views')),
                ('anime_type', models.IntegerField(choices=[(0, 'anime'), (1, 'series')], verbose_name='Anime Type')),
                ('studio', models.CharField(max_length=225, verbose_name='Studio')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('video', models.FileField(blank=True, null=True, upload_to='anime/videos/', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('video', models.FileField(upload_to='anime/videos/', verbose_name='Video')),
                ('number', models.IntegerField(unique=True, verbose_name='Number')),
                ('for_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Date')),
                ('for_anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('for_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.episode')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
    ]
