# Generated by Django 4.1.7 on 2023-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
