# Generated by Django 4.1.7 on 2023-03-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_episode_views_alter_anime_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='views',
        ),
    ]
